import { createDefaultModule, DefaultModuleContext, inject, LangiumServices, Module, PartialLangiumServices } from 'langium';
import { TontoGeneratedModule } from './generated/module';
import { TontoValidationRegistry, TontoValidator } from './tonto-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type TontoAddedServices = {
    validation: {
        TontoValidator: TontoValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type TontoServices = LangiumServices & TontoAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const TontoModule: Module<TontoServices, PartialLangiumServices & TontoAddedServices> = {
    validation: {
        ValidationRegistry: (injector) => new TontoValidationRegistry(injector),
        TontoValidator: () => new TontoValidator()
    }
};

/**
 * Inject the full set of language services by merging three modules:
 *  - Langium default services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 */
export function createTontoServices(context?: DefaultModuleContext): TontoServices {
    return inject(
        createDefaultModule(context),
        TontoGeneratedModule,
        TontoModule
    );
}
